info:
  application:
    boot-admin:
      enable: false
      url: http://127.0.0.1:906
    cs-verify:
      enable: true
      server-serial:
        - C02FD14HQ05R
      client-ip:
        - localhost
        - 0:0:0:0:0:0:0:1
        - 127.0.0.1
    liteflow:
      rule-sources:
        - liteflow/liteflow-demo.xml
spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://guokai.me:3306/mekatok?useSSL=false
          username: root
          password: root
  redis:
    host: 127.0.0.1
    port: 6379
knife4j:
  production: false
